package SyntaxProject;

import io.github.bonigarcia.wdm.WebDriverManager;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.Select;

public class SyntaxBasic {
    public static void main(String[] args) throws InterruptedException {
        WebDriverManager.chromedriver().setup();
        WebDriver driver=new ChromeDriver();
        driver.get("https://syntaxprojects.com/");
        driver.manage().window().maximize();
        Thread.sleep(1000);
        driver.findElement(By.id("btn_basic_example")).click();
        Thread.sleep(1000);
        /*driver.findElement(By.linkText("Simple Form Demo")).click();
        Thread.sleep(1000);
        driver.findElement(By.id("user-message")).sendKeys("Hello");
        driver.findElement(By.xpath("//button[@onclick='showInput();']")).click();
        Thread.sleep(1000);
        driver.findElement(By.id("sum1")).sendKeys("20");
        driver.findElement(By.id("sum2")).sendKeys("15");
        driver.findElement(By.xpath("//button[@onclick='return total()']")).click();
        Thread.sleep(1000);
        driver.navigate().back();
        driver.findElement(By.linkText("Check Box Demo")).click();
        driver.findElement(By.id("isAgeSelected")).click();
        driver.findElement(By.id("check1")).click();
        Thread.sleep(1000);
        driver.findElement(By.xpath("//*[@id=\"easycont\"]/div/div[2]/div[2]/div[2]/div[4]/label/input")).click();
        Thread.sleep(1000);
        driver.findElement(By.id("myCheck")).click();
        Thread.sleep(10000);
        driver.navigate().back();
        driver.findElement(By.linkText("Radio Buttons Demo")).click();
        driver.findElement(By.name("optradio")).click();
        driver.findElement(By.id("buttoncheck")).click();
        Thread.sleep(1000);
        driver.findElement(By.name("gender")).click();
        driver.findElement(By.xpath("//*[@id=\"easycont\"]/div/div[2]/div[2]/div[2]/div[2]/label[3]/input")).click();
        driver.findElement(By.xpath("//*[@id=\"easycont\"]/div/div[2]/div[2]/div[2]/button")).click();
        Thread.sleep(1000);
        driver.navigate().back();
        driver.findElement(By.linkText("Select Dropdown List")).click();
        Select dropdown=new Select(driver.findElement(By.id("select-demo")));
        dropdown.selectByValue("Monday");
        dropdown=new Select(driver.findElement(By.id("multi-select")));
        dropdown.selectByValue("Texas");
        driver.findElement(By.id("printMe")).click();
        Thread.sleep(1000);
        dropdown.selectByValue("Ohio");
        dropdown.selectByValue("New York");
        driver.findElement(By.id("printAll")).click();
        Thread.sleep(1000);
        driver.navigate().back();
        Thread.sleep(1000);
        driver.findElement(By.linkText("Javascript Alerts")).click();
        driver.findElement(By.cssSelector("#easycont > div > div.col-md-6.text-left > div:nth-child(4) > div.panel-body > button")).click();
        Thread.sleep(1000);
        driver.switchTo().alert().accept();
        driver.findElement(By.cssSelector("#easycont > div > div.col-md-6.text-left > div:nth-child(5) > div.panel-body > button")).click();
        Thread.sleep(1000);
        driver.switchTo().alert().accept();
        driver.findElement(By.cssSelector("#easycont > div > div.col-md-6.text-left > div:nth-child(6) > div.panel-body > button")).click();
        Thread.sleep(1000);
        driver.switchTo().alert().sendKeys("Talha Riaz");
        driver.switchTo().alert().accept();
        Thread.sleep(1000);
        driver.navigate().back();
        driver.findElement(By.linkText("Window Popup Modal")).click();
        Thread.sleep(1000);
        driver.navigate().back();
        driver.findElement(By.linkText("Bootstrap Alerts")).click();
        driver.findElement(By.id("autoclosable-btn-success")).click();
        driver.findElement(By.id("normal-btn-success")).click();
        driver.findElement(By.id("autoclosable-btn-warning")).click();
        driver.findElement(By.id("normal-btn-warning")).click();
        driver.findElement(By.id("autoclosable-btn-danger")).click();
        driver.findElement(By.id("normal-btn-danger")).click();
        driver.findElement(By.id("autoclosable-btn-info")).click();
        driver.findElement(By.id("normal-btn-info")).click();
        Thread.sleep(8000);
        driver.navigate().back();*/
        driver.findElement(By.linkText("Bootstrap Modals")).click();
        driver.findElement(By.linkText("Launch modal")).click();
        Thread.sleep(2000);
        driver.findElement(By.linkText("Close")).click();
        Thread.sleep(2000);
        driver.findElement(By.xpath("//a[@href='#myModal']")).click();
        Thread.sleep(2000);
        driver.findElement(By.xpath("//a[@href='#myModal2']")).click();
        Thread.sleep(2000);
        driver.findElement(By.xpath("//*[@id=\"myModal2\"]/div/div/div[6]/a[1]")).click();
        Thread.sleep(2000);
        driver.findElement(By.linkText("Save changes")).click();
        Thread.sleep(2000);
        driver.quit();
    }
}
